appcelerator/appc-install

lib/install.js
lib/run.js

Issue: [https://jira.appcelerator.org/browse/CLI-285](https://jira.appcelerator.org/browse/CLI-285)

[CLI-285] use installed appc after install

---

bin/appc

Issue: [https://jira.appcelerator.org/browse/CLI-291](https://jira.appcelerator.org/browse/CLI-291)

[CLI-291] fix bug with invoking "appc acs"

---

bin/appc

https://jira.appcelerator.org/browse/CLI-457

[CLI-457] Running appc alloy on Windows fails

---

bin/appc
lib/util.js

https://jira.appcelerator.org/browse/CLI-577

[CLI-577] add proxy logic

---

lib/use.js
lib/util.js
package.json

- When offline list the current installed versions
- Allow ```-o json``` to be used offline, listing the current installed versions
[JIRA Ticket](https://jira.appcelerator.org/browse/CLI-600)

[CLI-600] Add offline functionality to appc use

---

bin/appc

https://jira.appcelerator.org/browse/CLI-572

[CLI-572] appc acs and appc cloud reference different versions of ACS CLI

---

bin/appc

https://jira.appcelerator.org/browse/CLI-606

[CLI-606] appc -v to include npm version

---

bin/appc

https://jira.appcelerator.org/browse/CLI-606
Update according to comment in https://github.com/appcelerator/appc-install/pull/17

[CLI-606] modify environment variable name

---

lib/util.js

https://jira.appcelerator.org/browse/CLI-680

[CLI-680] add proxy settings in environment

---

lib/util.js

https://jira.appcelerator.org/browse/CLI-680

[CLI-680] add proxy settings in environment 4_0_X

---

lib/use.js

- Fixed always ```true``` condition
[JIRA Ticket](https://jira.appcelerator.org/browse/CLI-678)

[CLI-678] Any network errors are treated as being offline

---

lib/util.js

Related to https://github.com/appcelerator/appc-registry-server/pull/31
[Jira Ticket](https://jira.appcelerator.org/browse/CLI-723)

[CLI-723] Added session sid to request if logged in for appc use / install

---

lib/util.js

Fixed the regular expression causing the failure.

CLI-843 If you run "appc -v -o json", then Appc CLI NPM will not understand the "-o" flag

---

lib/install.js
lib/run.js
lib/util.js
package.json

https://jira.appcelerator.org/browse/CLI-827

[CLI-827] Module didn't register Error when switching node versions

---

bin/appc
lib/util.js
test/util_test.js

https://jira.appcelerator.org/browse/CLI-895

[CLI-895] CLI should not honor invalid url in proxy settings

---

lib/util.js

https://jira.appcelerator.org/browse/CLI-778

[CLI-778] Update check from the appcelerator npm does not inform the user of available update

---

bin/appc
package.json

https://jira.appcelerator.org/browse/CLI-759

[CLI-759] Use update-notifier to inform users that the appcelerator npm update is available

---

lib/use.js
package.json

Adding support to prerelease option to appc use command.

CLI-875 appc use command should allow --prerelease option

---

Gruntfile.js
lib/use.js
lib/util.js
test/use_test.js

https://jira.appcelerator.org/browse/CLI-976

[CLI-976] "appc use" breaks when list endpoint returns empty result

---

bin/appc
lib/util.js
test/mocks/mockca.pem
test/util_test.js

https://jira.appcelerator.org/browse/CLI-989

[CLI-989] added "strictSSL" & "cafile" to config

---

bin/appc
lib/util.js
package.json
test/mocks/mockca.pem
test/util_test.js

JIRA: https://jira.appcelerator.org/browse/CLI-989

[CLI-989] CLI not responding on self signed certificate

---

lib/install.js
package.json

JIRA: https://jira.appcelerator.org/browse/CLI-1003

[CLI-1003] If you run "appc setup" with the help flag, then "appc setup" will try to find/download the latest core first

---

bin/appc
lib/util.js
package.json

https://jira.appcelerator.org/browse/CLI-1024

[CLI-1024] appc ti info returned invalid json output

---

bin/appc
package.json

https://jira.appcelerator.org/browse/API-1310

[API-1310] EEXIST: file already exists, mkdir "C:\Users\****\.config"

---

lib/download.js
lib/use.js
lib/util.js
package.json
test/use_test.js

https://jira.appcelerator.org/browse/CLI-1054

[CLI-1054] Set connection timeout for appc use command

---

lib/run.js
lib/util.js
package.json

https://jira.appcelerator.org/browse/CLI-1077

[CLI-1077] CLI outputting non-JSON warning on npm rebuild

---

npm-shrinkwrap.json
package.json

JIRA: https://jira.appcelerator.org/browse/CLI-1090

[CLI-1090] Update notifier still getting installed

---

npm-shrinkwrap.json
package.json

JIRA: https://jira.appcelerator.org/browse/CLI-954
Removes unused bundled dependencies from package.json.

[CLI-954] Remove bundled dependencies from package.json

---

lib/util.js
package.json

https://jira.appcelerator.org/browse/CLI-868

[CLI-868] Added CLI version installation status as part of "appc use -o json" command output.

---

bin/appc
package.json

https://jira.appcelerator.org/browse/CLI-1176

[CLI-1176] appc -v with no cores installed throws TypeError

---

lib/run.js

https://jira.appcelerator.org/browse/CLI-1215

use spawn for cleaner code and not worry about buffer overflow

---

lib/util.js
package.json

https://jira.appcelerator.org/browse/CLI-1250

[CLI-1250] Add proxy pac file support

---

lib/util.js

Ref:  https://github.com/appcelerator/appc-platform-sdk/pull/73

Update urls for REG

---

lib/use.js
package-lock.json
package.json

https://jira.appcelerator.org/browse/CLI-1285

[CLI-1285]  stop the daemon prior to switch core

---

lib/install.js
package.json

https://jira.appcelerator.org/browse/CLI-1303

[CLI-1303] Call doNext callback when we dont install a native module

---

lib/install.js
package-lock.json
package.json
test/util_test.js

https://jira.appcelerator.org/browse/CLI-1319

[CLI-1319] Fix tar extract function naming

---

Jenkinsfile
package-lock.json
package.json

Merge when we're cool to mark this as latest 🤙

chore(release): v4.2.14

---

bin/appc
lib/run.js
lib/util.js
package.json

https://jira.appcelerator.org/browse/CLI-1375

feat: allow cli cores to declare their own minimum node version

---

lib/install.js
lib/use.js
lib/util.js
package-lock.json
package.json

Once we've restarted appcd, if we're selecting CLI 8.2.0 or above trigger plugin installation

feat(use): install daemon plugins after restarting the daemon
