- lib/use.js
Added a new output format for ``appc use`` command to print the list of versions in JSON format. It also prints the latest and active version in the JSON format.
> CLI-468 Print the latest versions stream in json format through appc use command

- lib/util.js
- In some cases the ```.version``` file does not get set correctly upon re-writing the file
[JIRA Ticket](https://jira.appcelerator.org/browse/CLI-485)
> [CLI-485] Fix version file not being set correctly

- lib/install.js
- lib/use.js
- Only set the ```.version``` after the installation has completed
[JIRA Ticket](https://jira.appcelerator.org/browse/CLI-580)
_____________________________________
```bash
appc use latest
appc use latest
```
> [CLI-580] Set version after installation has completed

- lib/download.js
- Fixes windows progress bar flickering issues
- Improves download performance
- Removed ```chalk.gray``` since colouring a space doesn't do anything
NOTE : I have disabled ```chalk``` colours on the progress bar for Windows. This was causing flickering and download issues.
[JIRA Ticket](https://jira.appcelerator.org/browse/CLI-434)
> [CLI-434] Fix progress bar flashing and download performance on Windows

- lib/use.js
On Windows ENOENT is returned instead of ENOTFOUND
> [CLI-600] Fix appc use offline use on Windows

- lib/use.js
On Windows ENOENT is returned instead of ENOTFOUND
> [CLI-600] Fix appc use offline use on Windows 4_0_X backport

- lib/use.js
- Using ``appc use latest``` offline sets the active version as the latest CLI version installed
[JIRA Ticket](https://jira.appcelerator.org/browse/CLI-600)
> [CLI-600] Allow 'appc use latest' offline 4_0_X

- lib/use.js
- Using ``appc use latest``` offline sets the active version as the latest CLI version installed
[JIRA Ticket](https://jira.appcelerator.org/browse/CLI-600)
> [CLI-600] Allow 'appc use latest' offline

- lib/use.js
- lib/util.js
- package.json
Modified ``appc use`` command to make sure it queries for latest version of appc-cli from registry. If versions are not available, then it falls back to the 1st top element in the returned list of packages.
> REG-55 Support tag versions for publishing appc-cli

- bin/appc
- lib/run.js
- package.json
This PR tries to address couple of issues 
- When user hit Terminate button after app lunch on Studio, then issues ``kill <appc-pid>``, but that doesn't kill any of the appc-cli processes.
- Liveview doesn't work from 2nd launch, as the processes are holding up from previous launch.
There are still different set of changes in appc-cli or appc-cli-titanium repo, trying to clean up titanium process.
> CLI-834 Serious problem of consumption of RAM

- bin/appc
- package.json
The option ``-v`` is not considered by our parsing code, and it is always ignored to load into ``opts``. So, whenever we execute ``appc -v`` command, it runs through software.appcelerator.com/api/appc/list results, and then, prints the version. That results in very slow response of the command when the registry server is not responsive. Since Studio runs this command a lot of times, these changes will improve performance of Studio as well.
> CLI-842 Improve performance of appc -v command

- lib/run.js
- package.json
The problem is that if we capture a signal such as SIGTERM and then process.exit after receiving it, a subprocess or subsequent process.on handler cannot handle it.  this is easily exposed running the arrow unit test suite with the 5.2.0 release + latest appcelerator npm.
this change means we simply wait for the exit to be send and only exit then.
> CLI-950 ensure that subprocess gets proper signal and exits

- package.json
Package version should be bump since we already published 4.2.9 with appc@6.2.0.
> Bump version 4.2.10-0

- lib/download.js
- lib/install.js
- package-lock.json
- package.json
https://jira.appcelerator.org/browse/CLI-1292
There's no need to add a `...` if we're showing a loading spinner, so this removes it. Looks a bit nicer, IMO!
> [CLI-1292] Remove redundant loading ellipsis

- .gitignore
- .vscode/settings.json
- lib/install.js
- package-lock.json
- package.json
JIRA: https://jira.appcelerator.org/browse/CLI-939
- Before running an npm install to recompile during an `appc use`, check if the module is compatible with the OS. If not don't install, avoiding an error
Question is whether we want to log it as I do below? Or just ignore it?
````
λ appc use 6.3.0 --force
Before you can continue, the latest Appcelerator software update needs to be downloaded.
Finding version 6.3.0  OK
Validating security checksum OK
Installing  OK
Compiling platform native modules
└ alloy/deasync OK
└ external-editor/spawn-sync  OK
└ bunyan/dtrace-provider  OK
└ bunyan/dtrace-provider  OK
└ arrow-flow/jsonpath  OK
└ bunyan/dtrace-provider  OK
└ ldapjs/dtrace-provider  OK
Installed!!
````
> [CLI-939] Check if module is compatible with OS before attempting to install

- .travis.yml
- lib/install.js
- package-lock.json
- package.json
- test/util_test.js
https://jira.appcelerator.org/browse/CLI-1319
This reduces the number of warnings from `npm audit` from `39 vulnerabilities (14 low, 15 moderate, 7 high, 3 critical)` to `8 low severity vulnerabilities`. We can reduce that number to 1, but it requires moving to 2.x of `grunt-appc-js` which will need to code re-linting I believe, so that will be done in a separate PR
For the production dependencies that were out of range, tar was the only one that needed code changes with `path` becoming `cwd`, pac-proxy-agent was bumped due to it dropping Node 4/5 support which doesn't matter to us really (ooops yes it does, that's what Travis uses 😆 ).
> [CLI-1319] Reduce number of vulnerabilities found by npm audit

- lib/install.js
- Update and simplify the `targz` method to only utilize the `tar` module
[JIRA Ticket](https://jira.appcelerator.org/browse/CLI-1326)
> [CLI-1326] Update targz method

- lib/install.js
- package-lock.json
- package.json
JIRA: https://jira.appcelerator.org/browse/CLI-1346
There appears to be no reason for the install process to run `npm install <package>@<version>` when downloading a CLI. This change instead runs `npm rebuild` in the root of the CLI core (similar to what's done on a node version change). Locally for me on MacOS this takes an `appc use <version>` from around 2 minutes to 30 seconds, but I imagine the real speedup will be for Windows users
> feat: use npm rebuild instead of npm install when installing a CLI core

- lib/install.js
- lib/use.js
- lib/util.js
- package-lock.json
- package.json
- test/util_test.js
There are currently two instances where the daemon is not correctly stopped when installing/selecting a CLI
* `appc use <version>` when Appc Studio is open and restarts the daemon in the previous version, as we kill the daemon _before_ writing `<version>` to disk as the active cli so Studio will restart the daemon from the previous version - 482d280c55894d1e1219784a9205b8f585fef3a2 
* Fix is to write the version before killing the daemon
* `appc use <version>` where version has to be downloaded - e5828d9ed897ec9cf98413bee9a8086c230ff459
* Fix is to kill the daemon in this code path
> Ensure daemon is stopped in all instances

- lib/util.js
- test/util_test.js
This allows us to ensure that we take the expected codepath during tests, otherwise we're entirely dependent on a users local config
> test: allow readConfig to be mocked

- lib/install.js
- package-lock.json
- package.json
Fixes CLI-1389
Mostly just a copy paste of https://github.com/appcelerator/appc-install/blob/master/lib/run.js#L64-L80 with just collecting stdout/stderr
> fix(use): use spawn to avoid max buffer error

- Jenkinsfile
- lib/install.js
- lib/util.js
- package-lock.json
- package.json
This will stop appcd from stopping the daemon and installing plugins whenever we need to recompile
the native modules, hopefully speeding the process up slightly.
Closes CLI-1408 and CLI-1407
> Skip appcd postinstall script, bump min node version
